import { row, inlineKeypad, btnSimple } from "../rubika/keypad.js";
import { renderPage } from "../core/render.js";
import { registerPage } from "../core/pages.js";
import { bold, mono } from "../rubika/format.js";
import { MENU, EMOJI } from "../config.js";
import { separator, fmtDateFa } from "../utils/text.js";
import { countUsers, countGroups, countEvent, allSettings, setSetting, getSetting, recentErrors } from "../core/db.js";
function deniedText(){return [`${EMOJI.lock} ${bold("دسترسی غیرمجاز")}`,"این بخش فقط برای مالک ربات در دسترس است."].join("\n");}
async function guardOwner(event){if(event.isOwnerFlag)return true;await renderPage({client:event.client,db:event.db,chat_id:event.chatId,menu:MENU.MAIN,rawText:deniedText(),inlineKeypad:inlineKeypad(row(btnSimple("nav.home",`${EMOJI.home} خانه`))),pushHistory:false});return false;}
function overviewText(){return [`${EMOJI.admin} ${bold("پنل مدیریت")}`,separator(),`به پنل مدیریت ربات خوش آمدید.`].join("\n");}
function overviewKeypad(){return inlineKeypad(row(btnSimple("admin.stats",`${EMOJI.chart} آمار`),btnSimple("admin.settings",`${EMOJI.settings} تنظیمات سراسری`)),row(btnSimple("admin.logs",`📄 لاگ خطاها`)),row(btnSimple("nav.back",`${EMOJI.back} بازگشت`),btnSimple("nav.home",`${EMOJI.home} خانه`)));}
export async function showAdminOverview(event){if(!(await guardOwner(event)))return;await renderPage({client:event.client,db:event.db,chat_id:event.chatId,menu:MENU.ADMIN,rawText:overviewText(),inlineKeypad:overviewKeypad()});}
export async function showAdminStats(event){if(!(await guardOwner(event)))return;const {db}=event;const [users,groups,startsToday,callbacksToday]=await Promise.all([countUsers(db),countGroups(db),countEvent(db,"start",86400000),countEvent(db,"callback",86400000)]);const text=[`${EMOJI.chart} ${bold("آمار ربات")}`,separator(),`تعداد کاربران ثبت‌شده: ${bold(users)}`,`تعداد گروه‌های فعال: ${bold(groups)}`,`تعداد /start در ۲۴ ساعت اخیر: ${bold(startsToday)}`,`تعداد کلیک روی دکمه در ۲۴ ساعت اخیر: ${bold(callbacksToday)}`].join("\n");await renderPage({client:event.client,db:event.db,chat_id:event.chatId,menu:MENU.ADMIN_STATS,rawText:text,inlineKeypad:adminBackKeypad()});}
const FEATURE_LABELS={feature_group_stats:"آمار گروه",feature_tools_menu:"منوی ابزارها",maintenance_mode:"حالت تعمیر و نگهداری"};
export async function showAdminSettings(event){if(!(await guardOwner(event)))return;const settings=await allSettings(event.db);const lines=[`${EMOJI.settings} ${bold("تنظیمات سراسری ربات")}`,separator()];const btns=[];for(const s of settings){const label=FEATURE_LABELS[s.key]||s.key;const on=s.value==="1";lines.push(`${on?"✅":"❌"} ${label}`);btns.push(btnSimple(`admin.toggle.${s.key}`,`${on?"خاموش کردن":"روشن کردن"}: ${label}`));}const rows=btns.map(b=>row(b));rows.push(row(btnSimple("admin.open",`${EMOJI.back} بازگشت`),btnSimple("nav.home",`${EMOJI.home} خانه`)));await renderPage({client:event.client,db:event.db,chat_id:event.chatId,menu:MENU.ADMIN_SETTINGS,rawText:lines.join("\n"),inlineKeypad:inlineKeypad(...rows)});}
export async function showAdminLogs(event){if(!(await guardOwner(event)))return;const errors=await recentErrors(event.db,8);const lines=[`📄 ${bold("لاگ خطاهای اخیر")}`,separator()];if(errors.length===0)lines.push("هیچ خطایی ثبت نشده است. ✅");else for(const e of errors){lines.push(`${mono(e.scope)} — ${fmtDateFa(e.ts)}`);lines.push(e.message);lines.push("");}await renderPage({client:event.client,db:event.db,chat_id:event.chatId,menu:MENU.ADMIN_LOGS,rawText:lines.join("\n"),inlineKeypad:adminBackKeypad()});}
function adminBackKeypad(){return inlineKeypad(row(btnSimple("admin.open",`${EMOJI.back} بازگشت به پنل مدیریت`),btnSimple("nav.home",`${EMOJI.home} خانه`)));}
export function register(router){registerPage(MENU.ADMIN,showAdminOverview);registerPage(MENU.ADMIN_STATS,showAdminStats);registerPage(MENU.ADMIN_SETTINGS,showAdminSettings);registerPage(MENU.ADMIN_LOGS,showAdminLogs);router.on("admin.open",showAdminOverview);router.on("admin.stats",showAdminStats);router.on("admin.settings",showAdminSettings);router.on("admin.logs",showAdminLogs);router.onPrefix("admin.toggle.",async(event,key)=>{if(!(await guardOwner(event)))return;const current=await getSetting(event.db,key,"0");await setSetting(event.db,key,current==="1"?"0":"1");await showAdminSettings(event);});}
