import { row, inlineKeypad, btnSimple, btnCalendar, btnNumberPicker, btnStringPicker, btnTextbox, btnSelection } from "../rubika/keypad.js";
import { renderPage } from "../core/render.js";
import { registerPage } from "../core/pages.js";
import { bold, mono, italic, underline, strike, spoiler, link } from "../rubika/format.js";
import { MENU, EMOJI } from "../config.js";
import { separator } from "../utils/text.js";
import { logError, getUiState } from "../core/db.js";
function overviewText() { return [`${EMOJI.tools} ${bold("ابزارها")}`, separator(), `مجموعه‌ای از قابلیت‌های واقعی API روبیکا که این ربات پشتیبانی می‌کند:`].join("\n"); }
function overviewKeypad() { return inlineKeypad(row(btnSimple("tools.location", `${EMOJI.location} ارسال موقعیت مکانی`)), row(btnSimple("tools.poll", `${EMOJI.poll} ساخت نظرسنجی`)), row(btnSimple("tools.pickers", `🧩 دکمه‌های انتخابی`)), row(btnSimple("tools.format", `🎨 قالب‌بندی متن`)), row(btnSimple("nav.back", `${EMOJI.back} بازگشت`), btnSimple("nav.home", `${EMOJI.home} خانه`))); }
function backKeypad() { return inlineKeypad(row(btnSimple("tools.open", `${EMOJI.back} بازگشت به ابزارها`), btnSimple("nav.home", `${EMOJI.home} خانه`))); }
export async function showToolsOverview(event) { await renderPage({ client:event.client, db:event.db, chat_id:event.chatId, menu:MENU.TOOLS, rawText:overviewText(), inlineKeypad:overviewKeypad() }); }
export async function runLocationDemo(event) { const {client,db,chatId}=event; try { await client.sendLocation(chatId,35.6997,51.3380); } catch(err) { await logError(db,"tools.location",err.message); } await renderPage({client,db,chat_id:chatId,menu:MENU.TOOLS_LOCATION,rawText:[`${EMOJI.location} ${bold("موقعیت مکانی ارسال شد.")}`,"پیام موقعیت به‌صورت جداگانه در چت شما ارسال شد."].join("\n"),inlineKeypad:backKeypad()}); }
export async function runPollDemo(event) { const {client,db,chatId}=event; try { await client.sendPoll(chatId,"کدام بخش ربات را بیشتر پسندیدید؟",["منوی اصلی","اطلاعات کاربر/گروه","ابزارها","تنظیمات"]); } catch(err) { await logError(db,"tools.poll",err.message); } await renderPage({client,db,chat_id:chatId,menu:MENU.TOOLS_POLL,rawText:[`${EMOJI.poll} ${bold("نظرسنجی ارسال شد.")}`].join("\n"),inlineKeypad:backKeypad()}); }
function pickersKeypad() { return inlineKeypad(row(btnCalendar("tools.pick.calendar","📅 انتخاب تاریخ","DatePersian")),row(btnNumberPicker("tools.pick.number","🔢 انتخاب عدد","1","10","5")),row(btnStringPicker("tools.pick.string","📋 انتخاب گزینه",["گزینه ۱","گزینه ۲","گزینه ۳"])),row(btnTextbox("tools.pick.text","📝 وارد کردن متن",{place_holder:"چیزی بنویسید..."})),row(btnSelection("tools.pick.selection","🎯 انتخاب از لیست",{selection_id:"tools_selection_demo",search_type:"None",get_type:"Local",is_multi_selection:false,items:[{text:"آیتم یک",type:"TextOnly"},{text:"آیتم دو",type:"TextOnly"},{text:"آیتم سه",type:"TextOnly"}]})),row(btnSimple("tools.open",`${EMOJI.back} بازگشت به ابزارها`),btnSimple("nav.home",`${EMOJI.home} خانه`))); }
export async function showPickers(event) { await renderPage({client:event.client,db:event.db,chat_id:event.chatId,menu:MENU.TOOLS_PICKERS,rawText:[`🧩 ${bold("دکمه‌های انتخابی")}`,separator(),`یکی از دکمه‌های زیر را امتحان کنید؛ نتیجه انتخاب شما همین‌جا نمایش داده می‌شود.`].join("\n"),inlineKeypad:pickersKeypad()}); }
export async function handlePickerResult(event) { const {client,db,chatId,value}=event; const state=await getUiState(db,chatId); const text=[`${EMOJI.ok} ${bold("مقدار دریافت شد:")}`,mono(value||"—")].join("\n"); if(state?.message_id){ try{await client.editMessageText(chatId,state.message_id,text); await client.editMessageKeypad(chatId,state.message_id,pickersKeypad()); return;}catch(err){await logError(db,"tools.pickerResult.edit",err.message);} } await client.sendMessage(chatId,text); }
export async function showFormatDemo(event) { const demo=[`🎨 ${bold("نمایش قالب‌بندی واقعی متن روبیکا")}`,separator(),`${bold("متن پررنگ")} | ${italic("متن مورب")} | ${underline("زیرخط‌دار")}`,`${strike("خط‌خورده")} | ${mono("متن تک‌فاصله (Mono)")}`,`${spoiler("متن مخفی (لمس کنید)")}`,`${link("لینک به مستندات روبیکا","https://rubika.ir")}`,"",`این‌ها از طریق metadata واقعی روبیکا (meta_data_parts) ارسال می‌شوند، نه صرفاً علامت‌های Markdown داخل متن.`].join("\n"); await renderPage({client:event.client,db:event.db,chat_id:event.chatId,menu:MENU.TOOLS_FORMAT,rawText:demo,inlineKeypad:backKeypad()}); }
export function register(router) { registerPage(MENU.TOOLS,showToolsOverview); registerPage(MENU.TOOLS_LOCATION,(e)=>showToolsOverview(e)); registerPage(MENU.TOOLS_POLL,(e)=>showToolsOverview(e)); registerPage(MENU.TOOLS_PICKERS,showPickers); registerPage(MENU.TOOLS_FORMAT,showFormatDemo); router.on("tools.open",showToolsOverview); router.on("tools.location",runLocationDemo); router.on("tools.poll",runPollDemo); router.on("tools.pickers",showPickers); router.on("tools.format",showFormatDemo); router.on("tools.pick.calendar",handlePickerResult); router.on("tools.pick.number",handlePickerResult); router.on("tools.pick.string",handlePickerResult); router.on("tools.pick.text",handlePickerResult); router.on("tools.pick.selection",handlePickerResult); }
